package Services.Command;

public enum Commands {
    LOGINUTENTE,
    LOGINAZIENDA,
    REGISTERUTENTE,
    REGISTERAZIENDA,
    GETFORNITORI,
    GETAGENTI,
    GETAZIENDE,
    GETLISTAPRODOTTI,
    GETLISTAPRODOTTIAZIENDA,
    INSERISCIPRODOTTO,
    EFFETTUAORDINE
}
